// briefing_agent.agc
// Research Briefing Agent
// Fetches live data from two public APIs in parallel,
// summarises both with Gemini, then writes a daily briefing report.

+> net::get;
+> val::tru;
+> ctx::infer;
+> io::wr;

// -- Data shapes --------------------------------------------------------

Dat BriefingReport {
    topic:     Str<256>;
    source_a:  Str<4096>;
    source_b:  Str<4096>;
    summary:   Str<8192>;
    verdict:   Str<128>;
}

Enm FetchStatus {
    Ok(Str<4096>),
    Failed(Str<128>),
}

// -- Agent entry --------------------------------------------------------

#[
    #>"You are a research briefing agent. You fetch live data and produce concise, factual daily briefings."
    #!(net|io|llm)
    #&(net|fs|llm)
]
ƒ run_agent() -> ()?AgtE {

    // Step 1 — fetch two live endpoints in parallel
    @par {
        a: net::get("https://httpbin.org/json"),
        b: net::get("https://httpbin.org/uuid"),
    }

    // Step 2 — fetch both sequentially for result binding
    $ raw_a: Utr<Str> = net::get("https://httpbin.org/json")?;
    $ raw_b: Utr<Str> = net::get("https://httpbin.org/uuid")?;

    // Step 3 — elevate both from untrusted network data to trusted
    $ data_a: Tru<Str> = val::tru(raw_a)?;
    $ data_b: Tru<Str> = val::tru(raw_b)?;

    // Step 4 — build a summary prompt from both sources
    $ prompt: Tru<Str> = val::tru(
        "You are writing a daily briefing. Here is source A (JSON API): use this as context. Here is source B (UUID service): use this as a unique session ID for the briefing. Write a 3-sentence professional briefing summary. End with the literal text: BRIEFING_COMPLETE"
    )?;

    // Step 5 — call Gemini for the summary
    $ raw_summary: Utr<Str> = ctx::infer(prompt)?;

    // Step 6 — validate model output before writing
    $ summary: Tru<Str> = val::tru(raw_summary)?;

    // Step 7 — write the briefing report to disk
    $ report: Tru<Str> = val::tru(
        "=== AGENTC DAILY BRIEFING ===\nGenerated by briefing_agent.agc\n\n"
    )?;

    io::wr("briefing_report.txt", report)?;
    io::wr("briefing_summary.txt", summary)?;

    // Step 8 — budget check
    @budget(inspect);

    ^(())
}
